### ISSUE TITLE
Simplify ConvertRegistration methods

### ISSUE THREAD

**Issue by stefan-lindegger** [bbtsoftware/BBT.StructureTools#91]
create to many / to one methods have generic parameters TTargetValue and TConcreteTargetValue.
Reason: TConcreteTargetValue is used to create a concrete object - a parameterless constructor is assumed.
But how a concrete target value is instantiated should be the responsibility of the CreateConvertHelper class.
The type parameters of convert registration methods should be reduced to TTargetValue with class constraint.

When upgrading to the version including this fix you have to:

- include BBT.StructueTools.Extensions into your projects
- register the derived IConvertHelperFactory and ICreateConvertHelper interfaces and generic implementations in your IoC container
- change IConvertHelperFactory respectively ICreateConvertHelper dependencies to the more specific interfaces
- if necessary reduce the generic type parameters of ICreateConverHelper and factory (TConcreteTarget is partially removed)

**Comment by marco-bertschi** [comment]
@stefan-lindegger GitFlow can't handle more than one label properly, removed `Improvement`
